<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_device_hubSmartZone</name>
   <tag></tag>
   <elementGuidId>0e501c6b-7818-4674-8564-31bc18999543</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>device_hubSmartZone</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;main_container toggle&quot;]/div[@class=&quot;smart-drawer&quot;]/div[2]/div[1]/div[1]/div[4]/div[1]/div[1]/div[1]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
