<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_time_to_leaveSmartPark</name>
   <tag></tag>
   <elementGuidId>f4dc3619-a986-460e-8ecb-fecbaecca11d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>time_to_leaveSmartPark</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;main_container toggle&quot;]/div[@class=&quot;smart-drawer&quot;]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
