<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_data_usageSmartData</name>
   <tag></tag>
   <elementGuidId>31f5d603-60a3-4a14-9a89-9cd52f81e2b1</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>data_usageSmartData</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;main_container toggle&quot;]/div[@class=&quot;smart-drawer&quot;]/div[2]/div[1]/div[1]/div[3]/div[1]/div[1]/div[1]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
