<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_personUsers</name>
   <tag></tag>
   <elementGuidId>04ff290c-abcf-454b-bd09-73465ea32d16</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>personUsers</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;mdl-js&quot;]/body[@class=&quot;nav-md&quot;]/div[3]/div[1]/div[1]/div[1]/div[1]/div[1]/div[5]/a[1]/div[1]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
