<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>3972eb4d-9082-4dba-a7c4-c607658c2a35</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://firebasestorage.googleapis.com/v0/b/sc-neptune-staging-1803.appspot.com/o/smartCloudConsole%2Fuserprofiles%2F77wKOspR14avkyu6qXJndEW4q7z2%2F77wKOspR14avkyu6qXJndEW4q7z2.png?alt=media&amp;token=1fef1863-cd99-4ce7-a5b6-008bc8019539</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;top_nav navbar-fixed-top&quot;]/div[@class=&quot;nav_menu&quot;]/nav[1]/ul[@class=&quot;nav navbar-nav navbar-right&quot;]/li[1]/a[@class=&quot;user-profile dropdown-toggle&quot;]/div[@class=&quot;user-avatar__inner&quot;]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
