<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_VB</name>
   <tag></tag>
   <elementGuidId>ad23e16d-4f47-40d0-ba69-ef4c7b9b22c6</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>user-initials</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VB</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;top_nav navbar-fixed-top&quot;]/div[@class=&quot;nav_menu&quot;]/nav[1]/ul[@class=&quot;nav navbar-nav navbar-right&quot;]/li[1]/a[@class=&quot;user-profile dropdown-toggle&quot;]/div[@class=&quot;user-avatar&quot;]/div[@class=&quot;user-avatar__inner&quot;]/span[@class=&quot;user-initials&quot;]</value>
   </webElementProperties>
</WebElementEntity>
